---
- name: rollback to previous version
  hosts: localhost
  vars:
    tenantid: ton98156
    apitoken: oIEJoD-lT9u6Cq8qCnhkv
    now: "{{ ansible_date_time.epoch|int * 1000}}"
    past: "{{ now|int - 7200000 }}" # 1h = 3600000   24h = 86400000
    payload: "{'State':'{{ State }}', 'ProblemID':'{{ ProblemID }}', 'ProblemTitle':'{{ ProblemTitle }}', 'ImpactedEntities':{{ ImpactedEntities }} }"

  tasks:
    - debug: var=vars

    - name: impacted entities
      set_fact:
        impactedEntities: "{{ImpactedEntities}}"

    - name: loop over entities
      debug: "entity: {{ item }}"
      with_items: "{{ impactedEntities }}"


    - name: fetch custom properties
      uri:
        url: https://{{tenantid}}.live.dynatrace.com/api/v1/events/?entityId={{item.entity}}&eventType=CUSTOM_DEPLOYMENT&from={{past}}&to={{now}}&Api-Token={{apitoken}}
        return_content: yes
      with_items: "{{ impactedEntities }}"
      register: customproperties
      ignore_errors: no

    - debug: var=customproperties


    - name: show deployment events
      set_fact:
        deployment_events: "{{item.json.events}}"
      with_items: "{{ customproperties.results }}"
      register: app_result

    - name: call remediation action
      uri:
        url: "{{ item.remediationAction }}"
        method: POST
        body_format: json
        body: "{{ vars | to_json }}"
        return_content: yes
      with_items: "{{ deployment_events  }}"
      register: remediationOutput


    - debug: var=remediationOutput


   # - name: fetch problem
   #   uri:
   #     url: https://{{tenantid}}.live.dynatrace.com/api/v1/problem/details/{{ProblemID}}?Api-Token={{apitoken}}
   #     return_content: yes
   #   register: webpage